name: Test Repository Request
description: "Request the creation of a new repository"
title: "Repository Request"
#lables:  ["Repo Request"]
body:

- type: markdown
  attributes:
    value: "## Kelloggcompany Repository Request!!!"
 
- type: markdown
  attributes:
    value: "Required fields are marked with an asterisk (*)."
- type: dropdown
  attributes:
    label: "Template"
    description: "What Template you want to use." 
    options:
        - Kellogg Basic 
        - Kellogg Advance
        - Kellogg Team Template
        - No Template
    default: 0
  validations:
      required: true

- type: input
  attributes:
      label: Repository name 
      description: Great repository names are short and memorable.
      placeholder: add here
      value: add here
  validations:
      required: true


- type: input
  attributes:
      label: Repository Description  
      description: Provide a detailed description of the repository, including its intended use, project objectives, and any relevant context. Be as specific as possible.
      placeholder: add here
      value: add here
  validations:
      required: true

- type: dropdown
  attributes:
    label: ACCESS AND PERMISSION
    description: Allowed only private repositories
    options:
        - Private Repository (Restricted access)      
    default: 0
  validations:
      required: true


- type: dropdown
  attributes:
    label: Add a README file
    description: All Repository's in Kelloggcompany should be included with README file.
    options:
      - "Yes"
    default: 0
  validations:
      required: true

- type: textarea
  attributes:
    label: ADDITIONAL NOTES
    description: Include any additional information, notes, or special instructions related to this repository request.
    value: add here
  validations:
      required: true


- type: checkboxes
  attributes:
    label: DONE
    description: By submitting this request, I acknowledge that I have read and understood the organization's policies and guidelines regarding repository creation and management.
    options:
    - label: I Confirm
      required: true
