name: Issue Approval Workflow

on:
  issues:
    types:
      - opened

jobs:
  check_approval:
    runs-on: ubuntu-latest

    steps:
      - name: Check for Approval Comment
        id: approval
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('Executing Issue Approvals')
            const issueNumber = context.payload.issue.number;
            console.log('Issue has been approved.')
            console.log(`Issue Number: ${issueNumber}`)
            const comments = await github.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
            });

            const approvalComment = comments.data.find(comment => {
              return comment.body.includes('Approve');
            });
            console.log(`Issue approvalComment: ${approvalComment}`)

            if (true) {
              core.setOutput('approved', 'true');
              console.log(`Issue true approvalComment: ${approvalComment}`)
            } else {
              core.setOutput('approved', 'false');
               console.log(`Issue false approvalComment: ${approvalComment}`)
            }
      - name: Check Approval and Execute Steps if not approved
        if: steps.approval.outputs.approved == 'false'
        run: |
          # Add the steps you want to execute if the issue is not approved.
          echo "The issue has been not been approved. Skipping additional steps."
      - name: Check Approval and Execute Steps fi approved
        if: steps.approval.outputs.approved == 'true'
        run: |
          # Add the steps you want to execute if the issue is approved.
          echo "The issue has been approved. Performing additional steps."
