name: Environment Based Approval

on:
  #issues:
    #types:
      #- opened
  workflow_run:
    workflows: ["Environment Approvals"]
    types:
      - completed

jobs:
  reject_repo_request:
    runs-on: ubuntu-latest
    env:
      issue-number: ${{ workflow.event.workflow_run.outputs.issue-number }}
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    environment: 
      name: dev
      url: "${{ github.event.issue.html_url  }}"
    steps:
      - name: Auto-reject
        run: |
          issue_body="${{ github.event.workflow_run.workflow_job[1].steps[0].output }}"
          # Add your rejection script here
          echo "Auto-rejecting $issue_body  $issue-number"
