name: Rejecct Repo Comment and Close Issue

on:
  #issues:
    #types:
      #- opened
  workflow_run:
    workflows: ["Request for Repo Creation"]
    types:
      - completed

jobs:
  reject_repo_request:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    environment: 
      name: dev
      url: "${{ github.event.issue.html_url  }}"
    steps:
      - name: Auto-reject
        run: |
          LOCATIONS_URL="${{ github.event.workflow_run.jobs_url }}"
          #LOCATIONS=$(curl -s -X GET -u "$TOKEN" "$LOCATIONS_URL")
          REPO_NAME="${{ github.repository }}"
          echo "Workflow Name: ${{ github.event.workflow_run.name }}"
          echo "REPO: $REPO_NAME"
          echo "LOCATIONS_URL: $LOCATIONS_URL"
          ISSUES=$(curl -s -X GET -u "$TOKEN" "https://api.github.com/repos/$REPO_NAME/issues?labels=${{ github.event.workflow_run.id }}")
          echo $ISSUES
          
          
