name: Rejecct Repo Comment and Close Issue

on:
  #issues:
    #types:
      #- opened
  workflow_run:
    workflows: ["Request for Repo Creations"]
    types:
      - completed

jobs:
  reject_repo_request:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    environment: 
      name: dev
      url: "${{ github.event.issue.html_url  }}"
    steps:
      - name: Auto-reject
        run: |
          LOCATIONS_URL="${{ github.event.workflow_run.jobs_url }}"
          LOCATIONS=$(curl -s -X GET -u "$TOKEN" "$LOCATIONS_URL")
          echo "BID ${{ needs.review_repo_request.outputs.issue-number }}"
          echo "NAME ${{ needs.review_repo_request.outputs.repo-name }}"
          echo "OWNER ${{ needs.review_repo_request.outputs.repo-owner }}"
          echo "DESC ${{ needs.review_repo_request.outputs.repo-desc }}"

          echo "Auto-rejecting \n $LOCATIONS"
          echo "${{ toJson(github.event.workflow_run) }}"
          
          echo ${{needs.review_repo_request.outputs.issue-url}}
          echo "Workflow Run ID: ${{ github.event.workflow_run.id }}"
          echo "Workflow Name: ${{ github.event.workflow_run.name }}"
          echo "Event: ${{ github.event.workflow_run.event }}"
          echo "Status: ${{ github.event.workflow_run.status }}"
          echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Created At: ${{ github.event.workflow_run.created_at }}"
          echo "Updated At: ${{ github.event.workflow_run.updated_at }}"
          echo "Head Commit: ${{ github.event.workflow_run.head_commit }}"
          echo "Repository: ${{ github.event.workflow_run.repository }}"
          echo "Head Repository: ${{ github.event.workflow_run.head_repository }}"
          echo "Actor: ${{ github.event.workflow_run.actor }}"
          echo "Sender: ${{ github.event.workflow_run.sender }}"
