name: Environment Based Approval

on:
  #issues:
    #types:
      #- opened
  workflow_run:
    workflows: ["Environment Approvals"]
    types:
      - completed

jobs:
  reject_repo_request:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    environment: 
      name: dev
      url: "${{ github.event.issue.html_url  }}"
    steps:
      - name: Auto-reject
        run: |
          issue_body="${{ toJson(github.event.workflow_run) }}"
          issue_boy="${{ github.event.workflow_run.workflow_job[1] }}"
          echo "Auto-rejecting $issue_body \n $issue_boy"
