name: Test Issue Comment
on:
  workflow_dispatch

jobs:
  test-issue-comment:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2   
    - name: Test Comment
      id: test-issue-comment
      env:
        HOOK_ID: ${{ vars.HOOK_ID }}
      run: |
        chmod +x scripts/comment.sh
        ./scripts/comment.sh                   
        
    - name: Issue Created
      if: success()
      run: echo "GitHub i
