name: Inline to Ext Script POC
on:
  workflow_dispatch
jobs:
  issue-comment:
    runs-on: ubuntu-latest
    outputs:
      issue-number: ${{ steps.test-issue-comment.outputs.issue-number }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2   
    - name: Test Inline to Ext Script
      id: test-issue-comment
      env:
        HOOK_ID: ${{ vars.HOOK_ID }}
        BASE_URL: ${{ vars.BASE_URL }}
        TOKENT: ${{ secrets.MY_PAT }}
        REPO_NAME: ${{ github.repository }}
        ORG_OR_OWNER: ${{ github.repository_owner }} 
        ISSUE_NUMBER: ${{ steps.test-issue-comment.outputs.issue-number }}
      run: |
        chmod +x scripts/comment.sh
        ./scripts/comment.sh
  update-issue-comment:
    runs-on: ubuntu-latest
    needs: [issue-comment]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2   
    - name: Test updated Inline to Ext Script
      id: update-issue-comment
      env:
        HOOK_ID: ${{ vars.HOOK_ID }}
        BASE_URL: ${{ vars.BASE_URL }}
        TOKENT: ${{ secrets.MY_PAT }}
        REPO_NAME: ${{ github.repository }}
        ORG_OR_OWNER: ${{ github.repository_owner }}
        ISSUE_NUMBER: ${{ needs.issue-comment.outputs.issue-number }} 
      run: |
        chmod +x scripts/comment.sh
        ./scripts/comment.sh
