name: Inline to Ext Script POC
on:
  workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    outputs:
      owner : ${{ steps.first_job_step2.outputs.owner }}
    steps:
    - name: Checkout code
      id: first_job_step1
      uses: actions/checkout@v2   
    - name: Test Inline to Ext Script
      id: first_job_step2
      env:
        HOOK_ID: ${{ vars.HOOK_ID }}
        BASE_URL: ${{ vars.BASE_URL }}
        TOKEN: ${{ secrets.MY_PAT }}
        REPO_NAME: ${{ github.repository }}
        ORG_OR_OWNER: ${{ github.repository_owner }} 
        ORGOROWNER: ${{ steps.first_job_step2.outputs.owner }}
      run: |
        chmod +x scripts/comment.sh
        ./scripts/comment.sh
  second_job:
    runs-on: ubuntu-latest
    needs: [first_job]
    steps:
    - name: Checkout code
      id: second_job_step1
      uses: actions/checkout@v2   
    - name: Test updated Inline to Ext Script
      id: second_job_step2
      env:
        HOOK_ID: ${{ vars.HOOK_ID }}
        BASE_URL: ${{ vars.BASE_URL }}
        TOKEN: ${{ secrets.MY_PAT }}
        REPO_NAME: ${{ github.repository }}
        ORG_OR_OWNER: ${{ github.repository_owner }}
        ORGOROWNER: ${{ needs.first_job.outputs.owner }} 
      run: |
        chmod +x scripts/comment.sh
        ./scripts/comment.sh
