name: Test Issue Comment
on:
  workflow_dispatch

jobs:
  test-issue-comment:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2   
    - name: Test Comment
      id: test-issue-comment
      env:
        HOOK_ID: ${{ vars.HOOK_ID }}
      run: |
        TOKEN="${{ secrets.MY_PAT }}"         
              COMMENT_CONTENT=$(<table.md)
              echo $COMMENT_CONTENT
              COMMENT_BODY="|ISSUE_NUMBER|ISSUE_URL|ISSUE_TITLE|ASS_LOGIN|ASS_TYPE|\n|------------|---------|-----------|---------|--------|\n|ISSUE_NUMBER|ISSUE_URL|ISSUE_TITLE|ASS_LOGIN|ASS_TYPE|"
              curl -X POST \
                -u "$TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/EIDIKO/secret-pub-repo/issues/249/comments" \
                -d '{
                  "body": "'"$COMMENT_BODY"'"
                }'                    
        
    - name: Issue Created
      if: success()
      run: echo "GitHub i
