name: Environment Based Approval

on:
  issues:
    types:
      - opened

jobs:
  requested:
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: "${{ github.event.issue.html_url  }}"
    steps:
      - name: Deploy to Dev
        run: |
          # Add your deployment script for the dev environment here
          issue_body="${{ github.event.issue.body }}"
          echo "Deploying to Dev environment $issue_body"


  approved_or_rejected:
    runs-on: ubuntu-latest
    environment: 
      name: uat
      url: "${{ github.event.issue.html_url  }}"
    steps:
      - name: Deploy to Dev
        run: |
          issue_body="${{ github.event.issue.body }}"
          # Add your deployment script for the dev environment here
          echo "Deploying to UAT environment $issue_body"
