name: Environment Based Approvals

on:
  push:
    branches:
      - main

jobs:
  requested:
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: https://github.com
    steps:
      - name: Deploy to Dev
        run: |
          # Add your deployment script for the dev environment here
          echo "Deploying to Dev environment"


  approved_or_rejected:
    runs-on: ubuntu-latest
    environment: 
      name: uat
      url: https://github.com
    steps:
      - name: Deploy to Dev
        run: |
          # Add your deployment script for the dev environment here
          echo "Deploying to UAT environment"
