name: Environment Based Approvals

on:
  push:
    branches:
      - main

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ['dev']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Dev
        run: |
          # Add your deployment script for the dev environment here
          echo "Deploying to Dev environment"

  deploy_uat:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ['uat']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to UAT
        run: |
          # Add your deployment script for the uat environment here
          echo "Deploying to UAT environment"
