name: Read Issue Template Properties

on:
  issues:
    types:
      - opened
      - edited

jobs:
  read_issue_template_properties:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read Issue Properties
      run: |
        issue_body="${{ github.event.issue.body }}"
        
        # Use regular expressions to extract template information
        template_type_match=$(echo "$issue_body" | grep -oP 'Template Type: \K(.+)')
        if [[ -n "$template_type_match" ]]; then
          echo "Template Type: $template_type_match"
        else
          echo "Template Type not found in issue body"
        fi
