name: Read Issue Template Properties

on:
  issues:
    types:
      - opened
      - edited

jobs:
  read_issue_template_properties:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read Issue Properties
      run: |
        issue_body="${{ github.event.issue.body }}"
        template_properties=$(echo "$issue_body" | \
          sed -n '/## Repository Request/,/^---/ p' | \
          grep -v -E '(^## Repository Request|^---$|^$|^\[.*\]$)' | \
          sed 's/^\** \(.*\): \(.*\)/\1: \2/')

        echo $template_properties
        
