name: Read Issue Template Properties

on:
  issues:
    types:
      - opened
      - edited

jobs:
  read_issue_template_properties:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read Issue Template Properties
      id: extract-properties
      run: |
        issue_body="${{ github.event.issue.body }}"
        property_names=("Name of Repository" "Purpose of Repository" "Team or Individual Requesting" "Primary Contact" "Repository Description" "Access and Permissions" "Access Control" "Branching Strategy" "Collaborators" "CI/CD and Automation" "Security and Compliance" "Additional Notes")
        
        for property_name in "${property_names[@]}"; do
          property_value=$(echo "$issue_body" | sed -n "/$property_name/,/## / p" | grep -v -E "^\[.*\]$" | sed -e "/$property_name/ s/^.*: *//")
          echo "************************************************"
          echo "$property_name : $property_value"
          echo "************************************************"
        done
    
        
