name: Read Issue Template Properties

on:
  issues:
    types:
      - opened
      - edited

jobs:
  extract_properties:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Repository Properties
        id: extract_properties
        run: |
          # Extract issue body from GitHub event payload
          issue_body="${{ github.event.issue.body }}"

          # Define an array of property names
          properties=("Name of Repository" "Purpose of Repository" "Team or Individual Requesting" "Primary Contact" "Repository Description" "Access and Permissions" "Branching Strategy" "Collaborators" "CI/CD and Automation" "Security and Compliance" "Additional Notes")

          # Initialize an associative array to store property values
          declare -A property_values

          # Use a for loop to extract property values
          for property in "${properties[@]}"; do
            value=$(echo "$issue_body" | grep -oP "(?<=\*\*$property:\*\* ).*")
            property_values["$property"]=$value
          done

          # Set the property values as job outputs
          for property in "${properties[@]}"; do
            echo "$property : property_values["$property"]"
          done
        shell: bash
    
        
