name: "Org Level Workflow(secret-pub-repo)"
on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '28 0 * * 1'

jobs:
  monitor-ssa-issues:
    runs-on: ubuntu-latest 
    steps:
      - name: Organization Level Webhook Testing
        id: org-level-webhook-teting
        env:
          HOOK_ID: ${{ vars.HOOK_ID }}
          issue-url: ${{ github.event.issue.html_url  }}
          TOKEN: ${{ secrets.MY_PAT }}   
          REPO_NAME: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          echo "Labeling issue with ${{ github.run_id }} ....."
          curl -X POST \
            -u "$TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO_NAME//pulls/281/files > response.json
          filename=$(jq -r '.[0].filename' response.json)   
          echo "files ${{ github.event.pull_request.changed_files }}"
          echo "${{ toJson(github.event.pull_request) }}"
          for file in ${{ github.event.pull_request.changed_files }}; do
            echo "file $file"
          done
          echo "ORG LEVEL WEBHOOK trigger"
