name: "Org Level Workflow(secret-pub-repo)"
on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '28 0 * * 1'

jobs:
  monitor-ssa-issues:
    runs-on: ubuntu-latest 
    steps:
      - name: Organization Level Webhook Testing
        id: org-level-webhook-teting
        env:
          HOOK_ID: ${{ vars.HOOK_ID }}
          issue-url: ${{ github.event.issue.html_url  }}
          TOKEN: ${{ secrets.MY_PAT }}   
          REPO_NAME: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          P_NUMBER: ${{ github.event.pull_request.number }}
          TT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Labeling issue with $P_NUMBER ....."
          SCA_API_RESPONSE=$(curl -s -i -X GET -u "$TT" "https://api.github.com/repos/$REPO_NAME/pulls/$P_NUMBER/files")        
          SCAs=$(echo "$SCA_API_RESPONSE" | awk -v RS='\r\n\r\n' 'NR==2')
          
          for SCA in $(echo "${SCAs}" | jq -r '.[] | @base64'); do
              _jq() {
                echo "${SCA}" | base64 --decode | jq -r "${1}"
              }
              echo "++++++++++++++++++++++++++++++++++"
              FILE_NAME=$(_jq '.filename')
              FILE_STATUS=$(_jq '.status')
              echo "NAME: $FILE_NAME"
              echo "STATUS: $FILE_STATUS"
              FILE_BASENAME=$(basename "$FILE_NAME")
              FILENAME="${FILE_BASENAME%.*}"
          done
          echo "ORG LEVEL WEBHOOK trigger"
