name: Test Environment Approvals test
on:
  issues:
    types:
      - opened
jobs:
  review_repo_request:
    runs-on: ubuntu-latest
    environment: 
      name: review
      url: "${{ github.event.issue.html_url  }}"
    steps:
      - name: Set variable issue_number value 
        id: extract-properties
        env:
          HOOK_ID: ${{ vars.HOOK_ID }}
        run: |
          echo "Neet to set a variable issue_number here"
  approve_repo_request:
    needs: [review_repo_request]
    runs-on: ubuntu-latest
    environment: 
      name: approve
      url: "${{ github.event.issue.html_url  }}"
    steps:
      - name: Deploy to Dev
        run: |
          issue_body="${{ github.event.issue.body }}"
          # Add your deployment script for the dev environment here
          echo "Deploying to UAT environment $issue_body"
  reject_repo_request:
      needs: [approve_repo_request]
      runs-on: ubuntu-latest
      if: ${{ needs.approve_repo_request.result == 'failure' }}
      environment:
        name: dev
        url: "${{ github.event.issue.html_url }}"
      steps:
        - name: Read Variable
          env:
            HOOK_ID: ${{ vars.HOOK_ID }} # Note: Change to secrets
          run: |
            echo "Need to print the variable here $issue_number"     
